# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Charts', '~> 3.3'
pod 'Alamofire', '~> 4.8.2'
  # Pods for Weather

end
